---
- hosts: all
  gather_facts: no
  become: yes
  vars_files:
    - vars/main.yml
  handlers:
    - include: handlers/main.yml
  tasks:
    - debug: var=rhel7cis_section4
    - include_role:
        name: section_4
      when: rhel7cis_section4 == true

    - debug: var=rhel7cis_section5
    - include_role:
        name: section_5
      when: rhel7cis_section5 == true

    