---

- name: restart postfix
  become: yes
  service:
      name: postfix
      state: restarted

- name: restart sshd
  become: yes
  service:
    name: sshd
    state: restarted

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted