---

- name: "5.4.1 Ensure password creation requirements are configured"
  lineinfile:
    state: present
    dest: /etc/security/pwquality.conf
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} = {{ item.value }}'
  with_items:
  - { key: 'minlen', value: '14' }
  - { key: 'minclass', value: '4' }
  when:
  - rhel7cis_rule_5_4_1

