---

- name: "5.2.1 Ensure sudo is installed"
  package:
    name: sudo
    state: present
  become: true
  when:
  - rhel7cis_rule_5_2_1

- name: "5.2.2 Ensure sudo commands use pty"
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults    use_pty'
    line: 'Defaults    use_pty'
    state: present
    validate: '/usr/sbin/visudo -cf %s'
  become: true
  when:
  - rhel7cis_rule_5_2_2

- name: "5.2.3 Ensure sudo log file exists"
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults    logfile="{{ rhel7cis_varlog_location }}"'
    line: 'Defaults    logfile="{{ rhel7cis_varlog_location }}"'
    state: present
    validate: '/usr/sbin/visudo -cf %s'
  when:
  - rhel7cis_rule_5_2_3