---

- name: "5.1.2 Ensure permissions on /etc/crontab are configured"
  file:
    dest: /etc/crontab
    owner: root
    group: root
    mode: 0600
  when:
  - rhel7cis_rule_5_1_2

- name: "5.1.3 Ensure permissions on /etc/cron.hourly are configured"
  file:
    dest: /etc/cron.hourly
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
  - rhel7cis_rule_5_1_3 

- name: "5.1.4 Ensure permissions on /etc/cron.daily are configured"
  file:
    dest: /etc/cron.daily
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
  - rhel7cis_rule_5_1_4

- name: "5.1.5 Ensure permissions on /etc/cron.weekly are configured"
  file:
    dest: /etc/cron.weekly
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
  - rhel7cis_rule_5_1_5

- name: "5.1.6 Ensure permissions on /etc/cron.monthly are configured"
  file:
    dest: /etc/cron.monthly
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
  - rhel7cis_rule_5_1_6

- name: "5.1.7 Ensure permissions on /etc/cron.d are configured"
  file:
    dest: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
  - rhel7cis_rule_5_1_7