---

- name: "5.6 Ensure root login is restricted to system console "
  block:
  - name: "5.6 Ensure root login is restricted to system console"
    command: cat /etc/securetty
    changed_when: no
    become: yes
    register: rhel_07_5_6_audit

  - name: "5.6 Ensure root login is restricted to system console"
    debug:
      msg:
      - "These are the consoles with root login access, please review:"
      # - "{{ rhel_07_5_6_audit.stdout_lines }}"
      - "{{ rhel_07_5_6_audit }}"
  when:
  - rhel7cis_rule_5_6

