---

- name: "5.5.1.1 Ensure password expiration is 365 days or less"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS {{ rhel7cis_pass['max_days'] }}"
  when:
  - rhel7cis_rule_5_5_1_1

- name: "5.5.1.2 Ensure minimum days between password changes is configured"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: "PASS_MIN_DAYS {{ rhel7cis_pass['min_days'] }}"
  when:
  - rhel7cis_rule_5_5_1_2

- name: "5.5.1.3 Ensure password expiration warning days is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: "PASS_WARN_AGE {{ rhel7cis_pass['warn_age'] }}"
  when:
  - rhel7cis_rule_5_5_1_3

- name: "5.5.3 Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: no
  failed_when: no
  when:
  - rhel7cis_rule_5_5_3

- name: "5.5.4 Ensure default user shell timeout is configured"
  blockinfile:
    create: yes
    mode: 0644
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
    marker: "# {mark} ANSIBLE MANAGED"
    block: |
      # Set session timeout - CIS ID RHEL-07-5.4.4
      TMOUT={{ rhel7cis_shell_session_timeout.timeout }}
      readonly TMOUT
      export TMOUT
  loop:
  - dest: "{{ rhel7cis_shell_session_timeout.file }}"
    state: present
  - dest: /etc/profile
    state: "{{ (rhel7cis_shell_session_timeout.file == '/etc/profile') | ternary('present', 'absent') }}"
  when:
  - rhel7cis_rule_5_5_4

- name: "5.5.5 Ensure default user umask is configured"
  block:
  - name: "5.5.5 Ensure default user umask is configured | Set umask for /etc/bashrc"
    replace:
      path: /etc/bashrc
      regexp: '(^\s+umask) 002'
      replace: '\1 027'

  - name: "5.5.5 Ensure default user umask is configured | Set umask for /etc/profile"
    replace:
      path: /etc/profile
      regexp: '(^\s+umask) 002'
      replace: '\1 027'
  when:
  - rhel7cis_rule_5_5_5