---

- name: "5.7 Ensure access to the su command is restricted | wheel group contains root | RHEL/CentOS"
  user:
    name: root
    groups: wheel
  when:
      - rhel7cis_rule_5_7
      - ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS"

- name: "5.7 Ensure access to the su command is restricted | Ubuntu"
  block:
      - name: "5.7 Ensure access to the su command is restricted | Create an empty group for use of su command"
        ansible.builtin.group:
            name: sugroup
            state: present

      - name: "5.7 Ensure access to the su command is restricted | Setting pam_wheel to use_uid"
        lineinfile:
            state: present
            dest: /etc/pam.d/su
            regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
            line: 'auth            required        pam_wheel.so use_uid group=sugroup'        
  when:
      - rhel7cis_rule_5_7
      - ansible_facts['distribution'] == "Ubuntu"