---

- name: "5.3.1 Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
    dest: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  when:
  - rhel7cis_rule_5_3_1

- name: "5.3.2 Ensure permissions on SSH private host key files are configured"
  block:
  - name: "5.3.2 Ensure permissions on SSH private host key files are configured"
    find:
      paths:
      - /etc/ssh
      patterns: 'ssh_host_*_key'
      recurse: true
      file_type: any
    register: rhel_07_5_3_2_priv_results

  - name: "5.3.2 Ensure permissions on SSH private host key files are configured"
    file:
      path: "{{ item.path }}"
      owner: root
      group: root
      mode: 0600
    loop: "{{ rhel_07_5_3_2_priv_results.files }}"
  when:
  - rhel7cis_rule_5_3_2

- name: "5.3.3 Ensure permissions on SSH public host key files are configured"
  block:
  - name: "5.3.3 Ensure permissions on SSH public host key files are configured"
    find:
      paths:
      - /etc/ssh
      patterns: 'ssh_host_*_key'
      recurse: true
      file_type: any
    register: rhel_07_5_3_3_pub_results

  - name: "5.3.3 Ensure permissions on SSH public host key files are configured"
    file:
      path: "{{ item.path }}"
      owner: root
      group: root
      mode: 0600
    loop: "{{ rhel_07_5_3_3_pub_results.files }}"
  when:
  - rhel7cis_rule_5_3_3

- name: "5.3.4 Ensure SSH access is limited"
  block:
    - name: "5.3.4 | L1 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowusers"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^AllowUsers"
        line: AllowUsers {{ rhel7cis_sshd['allowusers'] }}
      notify:
        - restart sshd
      when:
        - "rhel7cis_sshd['allowusers']|default('') | length > 0"

    - name: "5.3.4 | L1 | PATCH | Ensure SSH access is limited | Add line to sshd_config for allowgroups"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^AllowGroups"
        line: AllowGroups {{ rhel7cis_sshd['allowgroups'] }}
      notify:
        - restart sshd
      when:
        - "rhel7cis_sshd['allowgroups']|default('') | length > 0"

    - name: "5.3.4 | L1 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denyusers"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^DenyUsers"
        line: DenyUsers {{ rhel7cis_sshd['denyusers'] }}
      notify:
        - restart sshd
      when:
        - "rhel7cis_sshd['denyusers']|default('') | length > 0"

    - name: "5.3.4 | L1 | PATCH | Ensure SSH access is limited | Add line to sshd_config for denygroups"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "^DenyGroups"
        line: DenyGroups {{ rhel7cis_sshd['denygroups'] }}
      notify:
        - restart sshd
      when:
        - "rhel7cis_sshd['denygroups']|default('') | length > 0"
  when:
    - rhel7cis_rule_5_3_4

- name: "5.3.5 Ensure SSH LogLevel is appropriate"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#LogLevel|^LogLevel"
    line: 'LogLevel {{ rhel7cis_ssh_loglevel }}'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_5

- name: "5.3.7 Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^(#)?MaxAuthTries \d'
    line: 'MaxAuthTries 4'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_7

- name: "5.3.8 Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#IgnoreRhosts|^IgnoreRhosts"
    line: 'IgnoreRhosts yes'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_8

- name: "5.3.9 Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: ^#HostbasedAuthentication|^HostbasedAuthentication"
    line: 'HostbasedAuthentication no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_9

- name: "5.3.10 Ensure SSH root login is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin|^PermitRootLogin"
    line: 'PermitRootLogin no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_10

- name: "5.3.11 Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitEmptyPasswords|^PermitEmptyPasswords"
    line: 'PermitEmptyPasswords no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_11

- name: "5.3.12 Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#PermitUserEnvironment|^PermitUserEnvironment"
    line: 'PermitUserEnvironment no'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_12

- name: "5.3.13 Ensure only strong Ciphers are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Cipherss'
    line: "Ciphers {{ rhel7cis_sshd['ciphers'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_13

- name: "5.3.14 Ensure only strong MAC algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^MACs'
    line: "MACs {{ rhel7cis_sshd['macs'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_14

- name: "5.3.15 Ensure only strong Key Exchange algorithms are used"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^KexAlgorithms'
    line: "KexAlgorithms {{ rhel7cis_sshd['kex'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_15

- name: "5.3.16 Ensure SSH Idle Timeout Interval is configured"
  block:
  - name: "5.3.16 Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^ClientAliveInterval'
      line: "ClientAliveInterval {{ rhel7cis_sshd['clientaliveinterval'] }}"
    notify:
    - restart sshd

  - name: "5.3.16 Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
    lineinfile:
      state: present
      dest: /etc/ssh/sshd_config
      regexp: '^ClientAliveCountMax'
      line: "ClientAliveCountMax {{ rhel7cis_sshd['clientalivecountmax'] }}"
    notify:
    - restart sshd
  when:
  - rhel7cis_rule_5_3_16

- name: "5.3.17 Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#LoginGraceTime|^LoginGraceTime"
    line: "LoginGraceTime {{ rhel7cis_sshd['logingracetime'] }}"
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_17

- name: "5.3.18 Ensure SSH warning banner is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '^Banner'
    line: 'Banner /etc/issue.net'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_18

- name: "5.3.19 Ensure SSH PAM is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#UsePAM|^UsePAM"
    line: 'UsePAM yes'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_19

- name: "5.3.21 Ensure SSH MaxStartups is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#MaxStartups|^MaxStartups"
    line: 'MaxStartups 10:30:60'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_21

- name: "5.3.22 Ensure SSH MaxSessions is limited"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^#MaxSessions|^MaxSessions"
    line: 'MaxSessions {{ rhel7cis_ssh_maxsessions }}'
  notify:
  - restart sshd
  when:
  - rhel7cis_rule_5_3_22