---

- name: "5.5.1.1 Ensure password expiration is 365 days or less"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS {{ rhel7cis_pass['max_days'] }}"
  when:
  - rhel7cis_rule_5_5_1_1

- name: "5.5.1.2 Ensure minimum days between password changes is configured"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: "PASS_MIN_DAYS {{ rhel7cis_pass['min_days'] }}"
  when:
  - rhel7cis_rule_5_5_1_2

- name: "5.5.1.3 Ensure password expiration warning days is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: "PASS_WARN_AGE {{ rhel7cis_pass['warn_age'] }}"
  when:
  - rhel7cis_rule_5_5_1_3

- name: "SCORED | 5.5.3 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: no
  failed_when: no
  when:
  - rhel7cis_rule_5_5_3

