---

- name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: "install cramfs /bin/true"
            create: yes
            mode: '0600'

      - name: "1.1.1.1 Remove cramfs module"
        modprobe:
            name: cramfs
            state: absent
  when:
      - rhel7cis_rule_1_1_1_1

- name: "1.1.1.3 Ensure mounting of udf filesystems is disabled"
  block:
      - name: "1.1.1.3 Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: "install udf /bin/true"
            create: yes
            mode: '0600'

      - name: "1.1.1.3 Remove udf module"
        modprobe:
            name: udf
            state: absent
  when:
      - rhel7cis_rule_1_1_1_3

- name: "1.1.24 Disable USB Storage"
  block:
      - name: "1.1.24 Disable USB Storage | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install usb-storage(\\s|$)"
            line: "install usb-storage /bin/true"
            create: yes
            owner: root
            group: root
            mode: 0640

      - name: "1.1.24 Disable USB Storage | Edit modprobe config"
        modprobe:
            name: usb-storage
            state: absent
  when:
      - rhel7cis_rule_1_1_24