---

- name: "1.9 Ensure updates, patches, and additional security software are installed"
  package:
      name: "*"
      state: latest
  vars:
      ansible_python_interpreter: /bin/python
  when:
      - rhel7cis_rule_1_9
      - not system_is_ec2
