---

- name: "1.2.1 Ensure GPG keys are configured"
  block:
      - name: "1.2.1 Ensure GPG keys are configured | RedHat"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
        when:
            - ansible_distribution == "RedHat"

      - name: "1.2.1 Ensure GPG keys are configured | CentOS"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
        when:
            - ansible_distribution == "CentOS"
  when:
      - rhel7cis_rule_1_2_1