---

- name: "1.8.2 Ensure GDM login banner is configured"
  block:
      - name: "1.8.2 Ensure GDM login banner is configured | gdm profile"
        lineinfile:
            path: /etc/dconf/profile/gdm
            regexp: "^{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
            create: true
            mode: 0644
            owner: root
            group: root
        with_items:
            - {regexp: 'user-db', line: 'user-db:user' }
            - {regexp: 'system-db', line: 'system-db:gdm' }
            - {regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }

      - name: "1.8.2 Ensure GDM login banner is configured | banner"
        lineinfile:
            path: /etc/dconf/db/gdm.d/01-banner-message
            regexp: "^{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
            create: true
            mode: 0644
            owner: root
            group: root
        with_items:
            - { regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
            - { regexp: 'banner-message-enable', line: 'banner-message-enable=true' }
            - { regexp: 'banner-message-text', line: "banner-message-text='{{ rhel7cis_warning_banner }}' " }
  when:
      - not rhel7cis_gui
      - rhel7cis_rule_1_8_2

- name: "1.8.3 Ensure last logged in user display is disabled"
  block:
      - name: "1.8.3 Ensure last logged in user display is disabled | gdm profile"
        lineinfile:
            path: /etc/dconf/profile/gdm
            regexp: "^{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
            create: true
            mode: 0644
            owner: root
            group: root
        with_items:
            - {regexp: 'user-db', line: 'user-db:user' }
            - {regexp: 'system-db', line: 'system-db:gdm' }
            - {regexp: 'file-db', line: 'file-db:/usr/share/gdm/greeter-dconf-defaults' }

      - name: "1.8.3 Ensure last logged in user display is disabled | login screen"
        lineinfile:
            path: /etc/dconf/db/gdm.d/00-login-screen
            regexp: "^{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
            create: true
            mode: 0644
            owner: root
            group: root
        with_items:
            - { regexp: '\[org\/gnome\/login-screen\]', line: '[org/gnome/login-screen]' }
            - { regexp: 'disable-user-list', line: 'disable-user-list=true' }
  when:
      - not rhel7cis_gui
      - rhel7cis_rule_1_8_3

- name: "1.8.4 Ensure XDCMP is not enabled"
  lineinfile:
      path: /etc/gdm/custom.conf
      regexp: ^Enable=true
      state: absent
      create: true
      owner: root
      group: root
      mode: 0644
  when:
      - not rhel7cis_gui
      - rhel7cis_rule_1_8_4