---

- name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled"
  block:
      - name: "1.1.1.1 Ensure mounting of cramfs filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install cramfs(\\s|$)"
            line: "install cramfs /bin/true"
            create: yes
            mode: '0600'

      - name: "1.1.1.1 Remove cramfs module"
        modprobe:
            name: cramfs
            state: absent
  when:
      - rhel7cis_rule_1_1_1_1

- name: "1.1.1.3 Ensure mounting of udf filesystems is disabled"
  block:
      - name: "1.1.1.3 Ensure mounting of udf filesystems is disabled | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install udf(\\s|$)"
            line: "install udf /bin/true"
            create: yes
            mode: '0600'

      - name: "1.1.1.3 Remove udf module"
        modprobe:
            name: udf
            state: absent
  when:
      - rhel7cis_rule_1_1_1_3

- name: "1.1.6 Ensure /dev/shm is configured"
  block:
      - name: "1.1.6 Ensure separate partition exists for {{ required_mount }} | Absent"
        debug:
            msg: "Warning! {{ required_mount }} doesn't exist. This is a manual task"
        register: dev_shm_mount_absent
        changed_when: dev_shm_mount_absent.skipped is undefined
        when:
            - required_mount not in mount_names
      - name: "1.1.6 Ensure separate partition exists for {{ required_mount }} | Present"
        debug:
            msg: "Congratulations: {{ required_mount }} exists."
        register: dev_shm_mount_present
        when:
            - required_mount in mount_names
  vars:
      required_mount: '/dev/shm'
  when:
      - rhel7cis_rule_1_1_6

- name: "1.1.24 Disable USB Storage"
  block:
      - name: "1.1.24 Disable USB Storage | Edit modprobe config"
        lineinfile:
            dest: /etc/modprobe.d/CIS.conf
            regexp: "^(#)?install usb-storage(\\s|$)"
            line: "install usb-storage /bin/true"
            create: yes
            owner: root
            group: root
            mode: 0640

      - name: "1.1.24 Disable USB Storage | Edit modprobe config"
        modprobe:
            name: usb-storage
            state: absent
  when:
      - rhel7cis_rule_1_1_24