---

- name: "1.2.1 Ensure GPG keys are configured"
  block:
      - name: "1.2.1 Ensure GPG keys are configured | RedHat"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution|lower }}-release
        when:
            - ansible_distribution == "RedHat"

      - name: "1.2.1 Ensure GPG keys are configured | CentOS"
        command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
        when:
            - ansible_distribution == "CentOS"
  when:
      - rhel7cis_rule_1_2_1

- name: "1.2.2 Ensure package manager repositories are configured"
  block:
      - name: "1.2.2 Ensure package manager repositories are configured"
        shell: yum repolist
        changed_when: no
        register: repolist
        tags:
            - skip_ansible_lint

      - name: "1.2.2 Ensure package manager repositories are configured"
        debug:
            msg:
                - "Please check against site policy repos listed below match expected:"
                - "{{ repolist.stdout_lines }}"
  when:
      - rhel7cis_rule_1_2_2