---

- name: "1.3.1 Ensure AIDE is installed"
  block:
      - name: "1.3.1 Ensure AIDE is installed | Install"
        package:
            name: aide
            state: installed

      - name: "1.3.1 Ensure AIDE is installed | Started"
        shell: /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
        args:
            creates: /var/lib/aide/aide.db.gz
        changed_when: no
        failed_when: no
        async: "{{ ansible_check_mode | ternary(0, 45) }}"
  when:
      - rhel7cis_config_aide
      - rhel7cis_rule_1_3_1
  
- name: "1.3.2 Ensure filesystem integrity is regularly checked"
  cron:
      name: Run AIDE integrity check
      minute: "{{ rhel7cis_aide_cron['aide_minute'] | default('0') }}"
      hour: "{{ rhel7cis_aide_cron['aide_hour'] | default('5') }}"
      day: "{{ rhel7cis_aide_cron['aide_day'] | default('*') }}"
      month: "{{ rhel7cis_aide_cron['aide_month'] | default('*') }}"
      weekday: "{{ rhel7cis_aide_cron['aide_weekday'] | default('*') }}"
      job: "{{ rhel7cis_aide_cron['aide_job'] }}"
  when:
      - rhel7cis_rule_1_3_2