---

- name: "1.6.1.1 Ensure SELinux is installed"
  package:
      name: libselinux
      state: present
  when:
      - not rhel7cis_selinux_disable
      - rhel7cis_rule_1_6_1_1

- name: "1.6.1.2 Ensure SELinux is not disabled in bootloader configuration"
  replace:
      dest: /etc/default/grub
      regexp: '(selinux|enforcing)\s*=\s*0\s*'
  register: selinux_grub_patch
  ignore_errors: yes
  notify: grub2cfg
  when:
      - not rhel7cis_selinux_disable
      - rhel7cis_rule_1_6_1_2

- name: "1.6.1.3 Ensure SELinux policy is configured\n
         1.6.1.4 Ensure the SELinux state is enforcing or permissive"
  selinux:
      conf: /etc/selinux/config
      policy: "{{ rhel7cis_selinux_pol }}"
      state: "{{ rhel7cis_selinux_state }}"
  when:
      - not rhel7cis_selinux_disable
      - rhel7cis_rule_1_6_1_3
      - rhel7cis_rule_1_6_1_4

