---

- name: "1.5.1 Ensure core dumps are restricted"
  block:
      - name: "1.5.1 Ensure core dumps are restricted | Update limits.conf file"
        lineinfile:
            state: present
            dest: /etc/security/limits.conf
            regexp: '^#?\\*.*core'
            line: '*                hard    core            0'
            insertbefore: '^# End of file'

      - name: "1.5.1 Ensure core dumps are restricted | Set active kernel parameter"
        sysctl:
            name: fs.suid_dumpable
            value: '0'
            state: present
            reload: yes
            sysctl_set: yes
            ignoreerrors: yes

      - name: 1.5.1 Ensure core dumps are restricted | coredump.conf"
        lineinfile:
            dest: /etc/systemd/coredump.conf
            regexp: "{{ item.regex }}"
            line: "{{ item.line }}"
            create: yes
            mode: 0644
        loop:
            - { regex: '^Storage', line: 'Storage=none' }
            - { regex: '^ProcessSizeMax', line: 'ProcessSizeMax=0' }
  when:
      - rhel7cis_rule_1_5_1

- name: "1.5.2 Ensure XD/NX support is enabled"
  shell: dmesg|grep -E "NX|XD" | grep " active"
  changed_when: no
  when:
      - rhel7cis_rule_1_5_2

- name: "1.5.3 Ensure address space layout randomization (ASLR) is enabled"
  sysctl:
      name: kernel.randomize_va_space
      value: '2'
      state: present
      reload: yes
      sysctl_set: yes
      ignoreerrors: yes
  when:
      - rhel7cis_rule_1_5_3

- name: "1.5.4 Ensure prelink is not installed"
  package:
      name: prelink
      state: absent
  when:
      - rhel7cis_rule_1_5_4