---

- include: cis_1.1.x.yml
- include: cis_1.2.x.yml
- include: cis_1.3.x.yml
- include: cis_1.4.x.yml
- include: cis_1.5.x.yml
- include: cis_1.6.x.yml
- include: cis_1.7.x.yml
- include: cis_1.8.x.yml
- include: cis_1.9.x.yml