---

- name: "2.1.1 Ensure xinetd is not installed"
  package:
      name: xinetd
      state: absent
  when:
      - rhel7cis_rule_2_1_1

- name: "2.2.2 Ensure X11 Server components are not installed"
  package:
      state: absent
      name:
          - "@X Window System"
          - "xorg-x11*"
  when:
      - rhel7cis_rule_2_2_2