---

- name: "2.2.1.1 Ensure time synchronization is in use | service install"
  package:
      name: "{{ rhel7cis_time_synchronization }}"
      state: present
  when:
      - rhel7cis_rule_2_2_1_1

- name: "2.2.1.1 Ensure time synchronization is in use | service start"
  service:
      name: "{{ rhel7cis_time_synchronization }}d"
      state: started
      enabled: yes
  when:
      - rhel7cis_rule_2_2_1_1

# - name: "2.2.1.1 Ensure time synchronization is in use | service stop ntp"
#   service:
#       name: ntpd
#       state: stopped
#       enabled: no
#   when:
#       - rhel7cis_time_synchronization == "chrony"
#       - rhel7cis_rule_2_2_1_1

# - name: "2.2.1.1 Ensure time synchronization is in use | service stop chrony"
#   service:
#       name: chronyd
#       state: stopped
#       enabled: no
#   when:
#       - rhel7cis_time_synchronization == "ntp"
#       - rhel7cis_rule_2_2_1_1

- name: "2.2.1.2 Ensure chrony is configured"
  block:
      - name: "2.2.1.2 Ensure chrony is configured | modify /etc/chrony.conf"
        template:
            src: chrony.conf.j2
            dest: /etc/chrony.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.2.1.2 Ensure chrony is configured | modify /etc/sysconfig/chronyd"
        lineinfile:
            dest: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            state: present
            create: yes
            owner: root
            group: root
            mode: 0640
  when:
      - rhel7cis_time_synchronization == "chrony"
      - rhel7cis_rule_2_2_1_2

- name: "2.2.1.3 Ensure ntp is configured"
  block:
      - name: "2.2.1.3 Ensure ntp is configured | modify /etc/ntp.conf"
        template:
            src: ntp.conf.j2
            dest: /etc/ntp.conf
            owner: root
            group: root
            mode: 0644

      - name: "2.2.1.3 Ensure ntp is configured | modify /etc/sysconfig/ntpd"
        lineinfile:
            dest: /etc/sysconfig/ntpd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u ntp:ntp\""

      - name: "2.2.1.3 Ensure ntp is configured | modify /usr/lib/systemd/system/ntpd.service"
        lineinfile:
            dest: /usr/lib/systemd/system/ntpd.service
            regexp: "^(#)?ExecStart"
            line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
  when:
      - rhel7cis_time_synchronization == "ntp"
      - rhel7cis_rule_2_2_1_3

- name: "2.2.2 Ensure X11 Server components are not installed"
  package:
      state: absent
      name:
          - "@X Window System"
          - "xorg-x11*"
  when:
      - not rhel7cis_xwindows_required
      - rhel7cis_rule_2_2_2

# - name: "2.2.3 Ensure Avahi Server is not installed"
#   block:
#     - name: "2.2.3 Ensure Avahi Server is not installed | remove avahi"
#       package:
#         name: avahi
#         state: absent
            
#     - name: "2.2.3 Ensure Avahi Server is not installed | remove avahi-autoipd"
#       package:
#         name: avahi-autoipd
#         state: absent
#   when:
#       - not rhel7cis_avahi_server
#       - rhel7cis_rule_2_2_3

- name: "2.2.3 Ensure Avahi Server is not installed"
  yum:
    name:
        - avahi
        - avahi-autoipd
    state: absent
  when:
      - not rhel7cis_avahi_server
      - rhel7cis_rule_2_2_3

- name: "2.2.4 Ensure CUPS is not installed"
  package:
      name: cups
      state: absent
  when:
      - not rhel7cis_cups_server
      - rhel7cis_rule_2_2_4

- name: "2.2.5 Ensure DHCP Server is not installed"
  package:
      name: dhcp
      state: absent
  when:
      - not rhel7cis_dhcp_server
      - rhel7cis_rule_2_2_5

- name: "2.2.6 Ensure LDAP server is not installed"
  package:
      name: openldap-servers
      state: absent
  when:
      - not rhel7cis_ldap_server
      - rhel7cis_rule_2_2_6

- name: "2.2.7 Ensure DNS server is not installed"
  package:
      name: bind
      state: absent
  when:
      - not rhel7cis_named_server
      - rhel7cis_rule_2_2_7

- name: "2.2.8 Ensure FTP server is not installed"
  package:
      name: vsftpd
      state: absent
  when:
      - not rhel7cis_vsftpd_server
      - rhel7cis_rule_2_2_8

- name: "2.2.9 Ensure HTTP server is not installed"
  package:
      name: httpd
      state: absent
  when:
      - not rhel7cis_httpd_server
      - rhel7cis_rule_2_2_9

- name: "2.2.10 Ensure IMAP and POP3 server is not installed"
  package:
      name: dovecot
      state: absent
  when:
      - not rhel7cis_dovecot_server
      - rhel7cis_rule_2_2_10

- name: "2.2.11 Ensure Samba server is not installed"
  package:
      name: samba
      state: absent
  when:
      - not rhel7cis_smb_server
      - rhel7cis_rule_2_2_11

- name: "2.2.12 Ensure HTTP Proxy server is not installed"
  package:
      name: squid
      state: absent
  when:
      - not rhel7cis_squid_server
      - rhel7cis_rule_2_2_12

- name: "2.2.13 Ensure net-snmp is not installed"
  package:
      name: net-snmp
      state: absent
  when:
      - not rhel7cis_snmp_server
      - rhel7cis_rule_2_2_13

- name: "2.2.14 Ensure NIS server is not installed"
  package:
      name: ypserv
      state: absent
  when:
      - not rhel7cis_nis_server
      - rhel7cis_rule_2_2_14

- name: "2.2.15 Ensure telnet-server is not installed"
  package:
      name: telnet-server
      state: absent
  when:
      - not rhel7cis_telnet_server
      - rhel7cis_rule_2_2_15

- name: "2.2.16 Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify: restart postfix
  when:
      - not rhel7cis_is_mail_server
      - rhel7cis_rule_2_2_16

- name: "2.2.17 Ensure nfs-utils is not installed or the nfs-server service is masked"
  block:
      - name: "2.2.17 Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-utils"
        package:
            name: nfs-utils
            state: absent
        when:
            - not rhel7cis_nfs_rpc_server and not rhel7cis_nfs_server

      - name: "2.2.17 Ensure nfs-utils is not installed or the nfs-server service is masked | nfs-server"
        systemd:
            name: nfs-server
            masked: true
        when:
            - rhel7cis_nfs_rpc_server and not rhel7cis_nfs_server
  when:
      - rhel7cis_rule_2_2_17

- name: "2.2.18 Ensure rpcbind is not installed or the rpcbind services are masked"
  block:
      - name: "2.2.18 Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind"
        package:
            name: rpcbind
            state: absent
        when:
            - not rhel7cis_nfs_rpc_server and not rhel7cis_rpc_server

      - name: "2.2.18 Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
        systemd:
            name: rpcbind
            masked: true
        when:
            - rhel7cis_nfs_rpc_server and not rhel7cis_rpc_server

      - name: "2.2.18 Ensure rpcbind is not installed or the rpcbind services are masked | rpcbind-server"
        systemd:
            name: rpcbind.socket
            masked: true
        when:
            - rhel7cis_nfs_rpc_server and not rhel7cis_rpc_server
  when:
      - rhel7cis_rule_2_2_18

- name: "2.2.19 Ensure rsync is not installed or the rsyncd services are masked"
  block:
      - name: "2.2.19 Ensure rsync is not installed or the rsyncd services are masked | pkg removal"
        package:
            name: rsync
            state: absent

      - name: "2.2.19 Ensure rsync is not installed or the rsyncd services are masked | Mask"
        systemd:
            name: rsyncd
            masked: true
  when:
      - not rhel7cis_rsyncd_server
      - rhel7cis_rule_2_2_19