---

- name: "2.3.1 Ensure NIS client is not installed"
  package:
      name: ypbind
      state: absent
  when:
      - not rhel7cis_ypbind_required
      - rhel7cis_rule_2_3_1

- name: "2.3.2 Ensure rsh client is not installed"
  package:
      name: rsh
      state: absent
  when:
      - not rhel7cis_rsh_required
      - rhel7cis_rule_2_3_2

- name: "2.3.3 Ensure talk client is not installed"
  package:
      name: talk
      state: absent
  when:
      - not rhel7cis_talk_required
      - rhel7cis_rule_2_3_3

- name: "2.3.4 Ensure telnet client is not installed"
  package:
      name: telnet
      state: absent
  when:
      - not rhel7cis_telnet_required
      - rhel7cis_rule_2_3_4

- name: "2.3.5 Ensure LDAP client is not installed"
  package:
      name: openldap-client
      state: absent
  when:
      - not rhel7cis_openldap_clients_required
      - rhel7cis_rule_2_3_5