---

- name: "4.2.1.1 Ensure rsyslog is installed"
  package:
    name: "{{ rhel7cis_syslog }}"
    state: present
  vars:
    ansible_python_interpreter: /bin/python
  when:
    - rhel7cis_rule_4_2_1_1

- name: "4.2.1.2 Ensure rsyslog Service is enabled and running"
  service:
    name: rsyslog
    enabled: yes
    state: started
  when:
    - rhel7cis_rule_4_2_1_2
    - rhel7cis_syslog == 'rsyslog'

- name: "4.2.1.3 Ensure rsyslog default file permissions configured"
  lineinfile:
    dest: /etc/rsyslog.conf
    regexp: '^\$FileCreateMode'
    line: '$FileCreateMode 0640'
  notify: restart rsyslog
  when:
    - rhel7cis_rule_4_2_1_3

- name: "4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log hosts."
  block:
    - name: "4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log hosts. | When not log host"
      replace:
        path: /etc/rsyslog.conf
        regexp: '({{ item }})'
        replace: '#\1'
      with_items:
        - '^(\$ModLoad imtcp)'
        - '^(\$InputTCPServerRun)'
      notify: restart rsyslog
      when:
        - not rhel7cis_system_is_log_server

    - name: "4.2.1.6 Ensure remote rsyslog messages are only accepted on designated log hosts. | When log host"
      replace:
        path: /etc/rsyslog.conf
        regexp: '^#(.*{{ item }}.*)'
        replace: '\1'
      with_items:
        - 'ModLoad imtcp'
        - 'InputTCPServerRun'
      notify: restart rsyslog
      when:
        - rhel7cis_system_is_log_server
  when:
    - rhel7cis_rule_4_2_1_6

- name: "4.2.2.1 Ensure journald is configured to send logs to rsyslog"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[F|f]orward[T|t]o[S|s]yslog='
    line: "ForwardToSyslog=yes"
  when:
    - rhel7cis_rule_4_2_2_1

- name: "4.2.2.2 Ensure journald is configured to compress large log files"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[C|c]ompress='
    line: "Compress=yes"
  when:
    - rhel7cis_rule_4_2_2_2

- name: "4.2.2.3 Ensure journald is configured to write logfiles to persistent disk"
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: '^[S|s]torage='
    line: "Storage=persistent"
  when:
    - rhel7cis_rule_4_2_2_3

- name: "4.2.3 Ensure permissions on all logfiles are configured"
  command: find /var/log -type f -exec chmod g-wx,o-rwx "{}" + -o -type d -exec chmod g-wx,o-rwx "{}" +
  changed_when: no
  failed_when: no
  when:
    - rhel7cis_rule_4_2_3

- name: "4.2.4 Ensure logrotate is configured"
  find:
    paths: /etc/logrotate.d/
  register: log_rotates
  when:
    - rhel7cis_rule_4_2_4